In [1]:
import numpy as np

In [2]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
constant = np.full((3,3),5)
print(constant)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [5]:
random = np.random.random((3,3))
print(random)

[[0.67907612 0.70497502 0.33965591]
 [0.7064221  0.90360953 0.76615213]
 [0.97875385 0.4312397  0.98990231]]


In [6]:
sequence = np.arange(1, 10, 3)
print(sequence)

[1 4 7]


In [7]:
# Vector and Metrics and Tensor

In [8]:
vector = np.array([1,2,4])
print(vector)

[1 2 4]


In [9]:
matrix = np.array([[2,4,6],
                   [8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


In [10]:
tensor = np.array([[[1,2],[2,3],[3,4],[4,5]]])
print(tensor)

[[[1 2]
  [2 3]
  [3 4]
  [4 5]]]


In [11]:
# Proporties of Array's

In [12]:
arr = np.array([[1,2,3], 
                [4,5,6], 
                [7,8,9]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(3, 3)
2
9
int64


In [13]:
# Array Re-shape

In [16]:
arr = np.arange(12)
print(arr)

# Vector to Metrics
arr1 = arr.reshape((3,4))
print(arr1)

# Metrics to Vector
arr2 = arr1.flatten()
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# ravel (returns view, instead of copy) returns original
raveled = arr1.ravel()
print(raveled)
print(arr2.ravel()) 

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
# Transpose of Metrix
arr = np.array([[1,2,3], 
                [4,5,6], 
                [7,8,9]])

transpose = arr.T
print(f"{arr}\n")
print(f"Transposed:\n {transpose}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
