## Operations

In [1]:
import numpy as np

In [ ]:
# Indexing for vectors
array = np.array([1,2,3,4,5,6,7,8,9,0])
print("Basic Slicing", array[2:7])
print("With Step", array[1:9:2])
print("Negative indexing", array[-4])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 7


## Indexing in 2D array starts from 0th position. like 0th row and 0th column

In [ ]:
# For 2D array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

#targeting specific element
print(arr[1,2]) # first row and second element

6


In [11]:
# targeting a row
print(arr[1]) # first row

# targeting a column
print(arr[:,2]) # second column

[4 5 6]
[3 6 9]


## Sorting

In [12]:
unsorted = np.array([3,6,8,2,2,1,9,4,6,3])
print(unsorted)

sorted = np.sort(unsorted)
print(unsorted)

[3 6 8 2 2 1 9 4 6 3]
[3 6 8 2 2 1 9 4 6 3]
