## Operations

In [1]:
import numpy as np

In [2]:
# Indexing for vectors
array = np.array([1,2,3,4,5,6,7,8,9,0])
print("Basic Slicing", array[2:7])
print("With Step", array[1:9:2])
print("Negative indexing", array[-4])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 7


## Indexing in 2D array starts from 0th position. like 0th row and 0th column

In [3]:
# For 2D array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

#targeting specific element
print(arr[1,2]) # first row and second element

6


In [4]:
# targeting a row
print(arr[1]) # first row

# targeting a column
print(arr[:,2]) # second column

[4 5 6]
[3 6 9]


## Sorting

In [5]:
unsorted = np.array([3,6,8,2,2,1,9,4,6,3])
print(unsorted)

sorted = np.sort(unsorted)
print(unsorted)

[3 6 8 2 2 1 9 4 6 3]
[3 6 8 2 2 1 9 4 6 3]


In [6]:
# sorting method for 2D arrays

arr_2d = np.array([[6,3], [0,4],[9,5]])
print(arr_2d)
sorted_arr_2d = np.sort(arr_2d,axis=0)
print(f"Sorted array:\n {sorted_arr_2d}")

[[6 3]
 [0 4]
 [9 5]]
Sorted array:
 [[0 3]
 [6 4]
 [9 5]]


In [7]:
# Filtering arrays
numbers = np.array([1,2,8,4,3,6,5,9,])
even = numbers[numbers%2==0] # mask
print(f"even numbers: {even}")


even numbers: [2 8 4 6]


In [8]:
# Filter with mask
mask = numbers > 5
print(f"Numbers greater than 5: {numbers[mask]}")

Numbers greater than 5: [8 6 9]


## Fancy Indexing vs np.where()

In [9]:
indices = [1,2,3,4]
print(numbers[indices])

[2 8 4 3]


In [10]:
where_result = np.where(numbers>5)
print(numbers[where_result])

[8 6 9]


In [13]:
condition_array = np.where(numbers>5, numbers*1, numbers)
print(condition_array)

[1 2 8 4 3 6 5 9]
